name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync

      - name: Run pre-commit checks
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest tests/
